### ISSUE TITLE
Add a HTML table to the books page

### ISSUE THREAD

**Issue by andrewiankidd** [mackattack01/Joker-App#2]
with a list of books, year they came out

| Book                                    | Year  | summary |
| ------------------------------|-------|----------
| Batman: The Killing Joke     | 1988 |  explores the complex and dark relationship between Batman and the Joker, delving into the latter's potential origin

**Comment by mackattack01** [comment]
I made an information Table on the comics page listing comic name, release year and a summary of the comic :)
